import type { Machine, MachineGuide, StudioTheme, TrainingTemplate } from './types'

export const studioTheme: StudioTheme = {
  studioId: 'pilot-studio-vaihingen',
  productName: 'FitPath',
  studioName: 'Pilot Studio',
  location: 'Vaihingen an der Enz',
  inviteCode: 'FIT2026',
  primary: '#3abadd',
  accent: '#ff6b00',
}

const machineGuides: Record<string, MachineGuide> = {
  'leg-press': {
    summary: 'Geführte Druckbewegung für Beine und Gesäß mit stabiler Rückenauflage.',
    steps: [
      { title: 'Sitz einstellen', detail: 'Stelle die Rückenlehne so ein, dass die Knie in der Startposition etwa 90° bilden.' },
      { title: 'Füße positionieren', detail: 'Füße schulterbreit mittig aufsetzen, Knie folgen der Richtung der Fußspitzen.' },
      { title: 'Kontrolliert drücken', detail: 'Plattform wegdrücken, Knie nicht einrasten lassen und langsam zurückführen.' },
    ],
    targetMuscles: 'Oberschenkel · Gesäß',
    tempo: '2–1–2',
    breathing: 'Ausatmen beim Drücken',
    rangeOfMotion: 'Nur so tief, wie Becken und Rücken vollständig am Polster bleiben.',
    setup: 'Rückenlehne · Sicherheitsanschlag · Fußposition',
    commonMistakes: ['Knie nach innen kippen lassen', 'Becken am tiefsten Punkt einrollen', 'Knie vollständig durchdrücken'],
    safetyNotes: ['Sicherheitshebel vor dem ersten Satz prüfen', 'Mit einem leichten Probesatz beginnen'],
    motion: 'diagonal-press',
  },
  'hack-squat': {
    summary: 'Geführte Kniebeuge mit Schulterpolstern und fest vorgegebener Bewegungsbahn.',
    steps: [
      { title: 'Schultern anlegen', detail: 'Schulterpolster mittig platzieren, Rücken und Becken bleiben an der Auflage.' },
      { title: 'Stand wählen', detail: 'Füße schulterbreit und etwas vor dem Körper auf der Plattform positionieren.' },
      { title: 'Tief und ruhig', detail: 'Knie beugen, Fersen belasten und ohne Schwung wieder hochdrücken.' },
    ],
    targetMuscles: 'Oberschenkel · Gesäß',
    tempo: '3–1–2',
    breathing: 'Ausatmen beim Aufrichten',
    rangeOfMotion: 'Schmerzfreie Tiefe bei stabilem Rücken und vollständigem Fersenkontakt.',
    setup: 'Schulterpolster · Sicherheitsgriffe · Fußstand',
    commonMistakes: ['Fersen anheben', 'Knie nach innen führen', 'Zu schnell in die Tiefe fallen'],
    safetyNotes: ['Sicherheitsstopps vor Belastung kennenlernen', 'Keine ruckartige Richtungsänderung'],
    motion: 'diagonal-press',
  },
  'chest-press': {
    summary: 'Geführte Druckbewegung für Brust, vordere Schulter und Armstrecker.',
    steps: [
      { title: 'Sitzhöhe wählen', detail: 'Griffe starten ungefähr auf mittlerer Brusthöhe.' },
      { title: 'Schultern stabilisieren', detail: 'Schulterblätter leicht nach hinten unten ziehen und am Polster halten.' },
      { title: 'Nach vorn drücken', detail: 'Griffe gleichmäßig drücken und kontrolliert bis zur Startposition zurückführen.' },
    ],
    targetMuscles: 'Brust · Trizeps',
    tempo: '2–1–2',
    breathing: 'Ausatmen beim Drücken',
    rangeOfMotion: 'Ellbogen zurückführen, ohne dass die Schultern nach vorn kippen.',
    setup: 'Sitzhöhe · Startposition · Griffweite',
    commonMistakes: ['Schultern hochziehen', 'Handgelenke abknicken', 'Gewicht zurückfallen lassen'],
    safetyNotes: ['Ellbogen nicht hart durchstrecken', 'Gleichmäßige Bewegung beider Arme'],
    motion: 'horizontal-press',
  },
  butterfly: {
    summary: 'Bogenförmige Armführung zur gezielten Belastung der Brustmuskulatur.',
    steps: [
      { title: 'Sitz ausrichten', detail: 'Ellbogen und Griffe befinden sich ungefähr auf Brusthöhe.' },
      { title: 'Brust öffnen', detail: 'Rücken anlehnen, Schulterblätter stabilisieren und Ellbogen leicht beugen.' },
      { title: 'Arme schließen', detail: 'Arme ohne Schwung zusammenführen und langsam wieder öffnen.' },
    ],
    targetMuscles: 'Brust',
    tempo: '2–1–3',
    breathing: 'Ausatmen beim Schließen',
    rangeOfMotion: 'Nur so weit öffnen, wie die Schultern stabil und beschwerdefrei bleiben.',
    setup: 'Sitzhöhe · Startwinkel · Unterarmauflage',
    commonMistakes: ['Zu weit nach hinten öffnen', 'Schwung aus dem Oberkörper', 'Schultern zu den Ohren ziehen'],
    safetyNotes: ['Leichten Startwinkel wählen', 'Keine ruckartige Dehnung in der Endposition'],
    motion: 'arc-close',
  },
  'lat-pulldown': {
    summary: 'Vertikale Zugbewegung für den breiten Rücken und die Armbeuger.',
    steps: [
      { title: 'Polster fixieren', detail: 'Oberschenkelpolster so einstellen, dass du stabil sitzt.' },
      { title: 'Brust anheben', detail: 'Stange etwas breiter als schulterbreit greifen und Oberkörper leicht aufrichten.' },
      { title: 'Zur Brust ziehen', detail: 'Ellbogen nach unten führen, Stange zur oberen Brust und langsam zurück.' },
    ],
    targetMuscles: 'Latissimus · Bizeps',
    tempo: '2–1–3',
    breathing: 'Ausatmen beim Herunterziehen',
    rangeOfMotion: 'Arme oben fast strecken, ohne Schultern unkontrolliert hochzuziehen.',
    setup: 'Oberschenkelpolster · Griffweite · Sitzposition',
    commonMistakes: ['Stange in den Nacken ziehen', 'Stark nach hinten schwingen', 'Nur mit den Händen ziehen'],
    safetyNotes: ['Stange kontrolliert zurückführen', 'Nacken in neutraler Position halten'],
    motion: 'vertical-pull',
  },
  'assisted-pullup': {
    summary: 'Unterstützter Klimmzug mit Gegengewicht für eine kontrollierte Zugbewegung.',
    steps: [
      { title: 'Hilfe einstellen', detail: 'Mehr Gewicht bedeutet mehr Unterstützung; für saubere Wiederholungen wählen.' },
      { title: 'Sicher aufsteigen', detail: 'Griffe fassen und Knie nacheinander auf das bewegliche Polster setzen.' },
      { title: 'Körper hochziehen', detail: 'Brust in Richtung Griffe führen und langsam vollständig absenken.' },
    ],
    targetMuscles: 'Rücken · Bizeps',
    tempo: '2–1–3',
    breathing: 'Ausatmen beim Hochziehen',
    rangeOfMotion: 'Von fast gestreckten Armen bis Brusthöhe bei stabiler Körpermitte.',
    setup: 'Unterstützungsgewicht · Griff · Kniepolster',
    commonMistakes: ['Körper schwingen', 'Schultern hochziehen', 'Zu wenig Unterstützung wählen'],
    safetyNotes: ['Polster beim Auf- und Absteigen festhalten', 'Nicht vom beweglichen Polster abspringen'],
    motion: 'vertical-pull',
  },
  'seated-row': {
    summary: 'Horizontaler Zug mit Brustpolster für oberen Rücken und hintere Schulter.',
    steps: [
      { title: 'Sitz einstellen', detail: 'Brust liegt am Polster, Griffe sind mit fast gestreckten Armen erreichbar.' },
      { title: 'Neutral greifen', detail: 'Brust anheben, Schultern tief und Handgelenke gerade halten.' },
      { title: 'Ellbogen zurück', detail: 'Griffe zum Körper ziehen, Schulterblätter zusammenführen und langsam lösen.' },
    ],
    targetMuscles: 'Oberer Rücken · Bizeps',
    tempo: '2–1–3',
    breathing: 'Ausatmen beim Ziehen',
    rangeOfMotion: 'Bis die Ellbogen am Körper vorbeiziehen, ohne die Brust vom Polster zu lösen.',
    setup: 'Sitzhöhe · Brustpolster · Griffposition',
    commonMistakes: ['Brust vom Polster lösen', 'Schultern hochziehen', 'Handgelenke einknicken'],
    safetyNotes: ['Gewicht nicht zurückschnellen lassen', 'Bewegung symmetrisch ausführen'],
    motion: 'horizontal-pull',
  },
  'cable-row': {
    summary: 'Freierer horizontaler Kabelzug für Rücken, Armbeuger und Rumpfstabilität.',
    steps: [
      { title: 'Füße abstellen', detail: 'Knie leicht gebeugt, Rücken lang und Griff sicher gefasst.' },
      { title: 'Oberkörper stabil', detail: 'Aufrecht sitzen und Bauchspannung halten.' },
      { title: 'Zum Bauch ziehen', detail: 'Ellbogen nah am Körper führen und Kabel langsam nach vorn lassen.' },
    ],
    targetMuscles: 'Rücken · Bizeps',
    tempo: '2–1–3',
    breathing: 'Ausatmen beim Ziehen',
    rangeOfMotion: 'Arme nach vorn führen, ohne den unteren Rücken rund werden zu lassen.',
    setup: 'Fußstütze · Griffaufsatz · Sitzabstand',
    commonMistakes: ['Aus dem Rücken schwingen', 'Schultern nach vorn fallen lassen', 'Kabel zurückschnellen lassen'],
    safetyNotes: ['Gewichtsstapel vor dem Aufstehen absetzen', 'Griff erst lösen, wenn das Kabel entlastet ist'],
    motion: 'horizontal-pull',
  },
  'shoulder-press': {
    summary: 'Geführte Überkopfbewegung für Schultern und Armstrecker.',
    steps: [
      { title: 'Sitzhöhe wählen', detail: 'Griffe starten knapp oberhalb der Schultern.' },
      { title: 'Rücken anlegen', detail: 'Füße fest aufstellen und Rücken vollständig am Polster halten.' },
      { title: 'Nach oben drücken', detail: 'Griffe kontrolliert hochdrücken und ohne Aufprall absenken.' },
    ],
    targetMuscles: 'Schultern · Trizeps',
    tempo: '2–1–2',
    breathing: 'Ausatmen beim Hochdrücken',
    rangeOfMotion: 'Bis kurz vor die vollständige Ellbogenstreckung, schmerzfrei absenken.',
    setup: 'Sitzhöhe · Griffart · Startposition',
    commonMistakes: ['Hohlkreuz verstärken', 'Schultern hochziehen', 'Ellbogen hart einrasten'],
    safetyNotes: ['Leichten Probesatz für die Sitzhöhe nutzen', 'Bei Schulterbeschwerden Trainer fragen'],
    motion: 'vertical-press',
  },
  'leg-curl': {
    summary: 'Geführte Kniebeugung zur gezielten Belastung der hinteren Oberschenkel.',
    steps: [
      { title: 'Achse ausrichten', detail: 'Kniegelenk liegt auf Höhe des markierten Drehpunkts.' },
      { title: 'Polster anlegen', detail: 'Rollenpolster knapp oberhalb der Ferse positionieren und Oberschenkel fixieren.' },
      { title: 'Beine beugen', detail: 'Fersen kontrolliert heranziehen und Gewicht langsam zurückführen.' },
    ],
    targetMuscles: 'Beinbeuger',
    tempo: '2–1–3',
    breathing: 'Ausatmen beim Beugen',
    rangeOfMotion: 'So weit beugen, wie Becken und Oberschenkel ruhig am Polster bleiben.',
    setup: 'Drehachse · Fußpolster · Oberschenkelpolster',
    commonMistakes: ['Becken anheben', 'Zu großes Bewegungstempo', 'Polster direkt auf der Achillessehne'],
    safetyNotes: ['Knieachse sorgfältig ausrichten', 'Gewicht langsam in die Streckung zurückführen'],
    motion: 'curl',
  },
  abdominal: {
    summary: 'Geführte Rumpfbeugung zur kontrollierten Aktivierung der Bauchmuskulatur.',
    steps: [
      { title: 'Sitz einstellen', detail: 'Drehpunkt der Maschine ungefähr auf Höhe der Körpermitte ausrichten.' },
      { title: 'Polster anlegen', detail: 'Füße fixieren und Brust- oder Schulterpolster bequem anlegen.' },
      { title: 'Rumpf einrollen', detail: 'Rippen in Richtung Becken führen und langsam wieder aufrichten.' },
    ],
    targetMuscles: 'Bauchmuskulatur',
    tempo: '2–1–3',
    breathing: 'Ausatmen beim Einrollen',
    rangeOfMotion: 'Kleine kontrollierte Beugung ohne Zug aus Armen oder Hüfte.',
    setup: 'Sitzposition · Fußstütze · Startwinkel',
    commonMistakes: ['Mit den Armen ziehen', 'Aus der Hüfte schwingen', 'Zu weit nach hinten überstrecken'],
    safetyNotes: ['Nacken entspannt halten', 'Bewegungsumfang klein und kontrolliert beginnen'],
    motion: 'crunch',
  },
  'back-extension': {
    summary: 'Geführte Hüft- und Rumpfstreckung für Rückenstrecker und Gesäß.',
    steps: [
      { title: 'Polster ausrichten', detail: 'Rückenpolster liegt bequem am oberen Rücken, Füße stehen stabil.' },
      { title: 'Neutral starten', detail: 'Bauchspannung aufbauen und Blick gerade halten.' },
      { title: 'Aufrichten', detail: 'Oberkörper bis zur neutralen Position strecken und langsam zurückführen.' },
    ],
    targetMuscles: 'Rückenstrecker · Gesäß',
    tempo: '2–1–3',
    breathing: 'Ausatmen beim Aufrichten',
    rangeOfMotion: 'Nur bis zur geraden Körperlinie, nicht in die Überstreckung.',
    setup: 'Rückenpolster · Fußposition · Startwinkel',
    commonMistakes: ['Überstrecken', 'Schwung verwenden', 'Kopf in den Nacken legen'],
    safetyNotes: ['Kleine Bewegungsamplitude beginnen', 'Wirbelsäule während der Bewegung neutral halten'],
    motion: 'extension',
  },
}

const machine = (
  id: string,
  code: string,
  name: string,
  zone: string,
  muscleGroups: Machine['muscleGroups'],
  routeOrder: number,
  alternativeIds: string[],
  instruction: string,
  active = true,
): Machine => ({
  studioId: studioTheme.studioId,
  id,
  code,
  name,
  photoUrl: `/machines/${id}.jpg`,
  zone,
  muscleGroups,
  active,
  routeOrder,
  alternativeIds,
  instruction,
  guide: machineGuides[id],
})

export const machines: Machine[] = [
  machine(
    'leg-press',
    'M04',
    'Beinpresse',
    'Kraft · Zone A',
    ['legs'],
    1,
    ['hack-squat'],
    'Rücken anlehnen, Knie kontrolliert beugen und niemals vollständig durchdrücken.',
  ),
  machine(
    'hack-squat',
    'M05',
    'Hackenschmidt',
    'Kraft · Zone A',
    ['legs'],
    2,
    ['leg-press'],
    'Füße schulterbreit, Bewegung langsam und im schmerzfreien Bereich ausführen.',
  ),
  machine(
    'chest-press',
    'M07',
    'Brustpresse',
    'Kraft · Zone B',
    ['chest'],
    3,
    ['butterfly'],
    'Griffe auf Brusthöhe einstellen und die Schulterblätter am Polster halten.',
  ),
  machine(
    'butterfly',
    'M08',
    'Butterfly',
    'Kraft · Zone B',
    ['chest'],
    4,
    ['chest-press'],
    'Ellbogen leicht gebeugt lassen und die Bewegung ohne Schwung schließen.',
  ),
  machine(
    'lat-pulldown',
    'M12',
    'Latzug',
    'Kraft · Zone C',
    ['back'],
    5,
    ['assisted-pullup'],
    'Brust anheben, Stange kontrolliert zur oberen Brust ziehen und nicht in den Nacken.',
  ),
  machine(
    'assisted-pullup',
    'M13',
    'Klimmzug assistiert',
    'Kraft · Zone C',
    ['back'],
    6,
    ['lat-pulldown'],
    'Körperspannung halten und die Unterstützung so wählen, dass die Wiederholungen sauber bleiben.',
  ),
  machine(
    'seated-row',
    'M15',
    'Rudermaschine',
    'Kraft · Zone C',
    ['back'],
    7,
    ['cable-row'],
    'Brust am Polster halten, Ellbogen nah am Körper nach hinten führen.',
  ),
  machine(
    'cable-row',
    'M16',
    'Kabelrudern',
    'Kraft · Zone C',
    ['back'],
    8,
    ['seated-row'],
    'Aufrecht sitzen und den Griff ohne Rückenschwung zum Körper ziehen.',
  ),
  machine(
    'shoulder-press',
    'M18',
    'Schulterpresse',
    'Kraft · Zone D',
    ['shoulders'],
    9,
    [],
    'Sitz so einstellen, dass die Griffe knapp über Schulterhöhe starten.',
  ),
  machine(
    'leg-curl',
    'M21',
    'Beinbeuger',
    'Kraft · Zone A',
    ['legs'],
    10,
    [],
    'Kniegelenk an der Drehachse ausrichten und das Gewicht kontrolliert absenken.',
  ),
  machine(
    'abdominal',
    'M23',
    'Bauchmaschine',
    'Functional · Zone E',
    ['core'],
    11,
    ['back-extension'],
    'Aus der Bauchmuskulatur einrollen und nicht mit den Armen ziehen.',
  ),
  machine(
    'back-extension',
    'M26',
    'Rückenstrecker',
    'Functional · Zone E',
    ['core', 'back'],
    12,
    ['abdominal'],
    'Wirbelsäule neutral halten und nur bis zur aufrechten Position strecken.',
  ),
]

export const trainingTemplates: TrainingTemplate[] = [
  {
    studioId: studioTheme.studioId,
    id: 'balanced-start',
    name: 'Balanced Start',
    description: 'Ein klarer Ganzkörper-Einstieg mit kurzen Wegen und kontrollierter Belastung.',
    goals: ['general_fitness', 'weight_control'],
    levels: ['beginner', 'intermediate'],
    supportedDays: [2, 3],
    supportedDurations: [30, 45, 60],
    machineIds: ['leg-press', 'chest-press', 'lat-pulldown', 'seated-row', 'abdominal', 'back-extension'],
    dayBlueprints: [
      {
        id: 'balanced-a',
        name: 'Ganzkörper Basis',
        machineIds: ['leg-press', 'chest-press', 'lat-pulldown', 'seated-row', 'abdominal'],
      },
      {
        id: 'balanced-b',
        name: 'Ganzkörper Variation',
        machineIds: ['hack-squat', 'butterfly', 'assisted-pullup', 'cable-row', 'back-extension'],
      },
    ],
    targetSets: 3,
    repMin: 8,
    repMax: 12,
    weightStep: 2.5,
    approvedBy: 'Trainerteam Pilot Studio',
  },
  {
    studioId: studioTheme.studioId,
    id: 'strength-foundation',
    name: 'Strength Foundation',
    description: 'Mehr Struktur und Trainingsvolumen für einen nachhaltigen Kraftaufbau.',
    goals: ['muscle_gain'],
    levels: ['beginner', 'intermediate', 'advanced'],
    supportedDays: [3, 4, 5],
    supportedDurations: [45, 60, 90],
    machineIds: [
      'leg-press',
      'leg-curl',
      'chest-press',
      'lat-pulldown',
      'seated-row',
      'shoulder-press',
      'abdominal',
      'back-extension',
    ],
    dayBlueprints: [
      {
        id: 'strength-a',
        name: 'Unterkörper & Mitte',
        machineIds: ['leg-press', 'leg-curl', 'abdominal', 'back-extension'],
      },
      {
        id: 'strength-b',
        name: 'Oberkörper Zug',
        machineIds: ['lat-pulldown', 'seated-row', 'assisted-pullup', 'cable-row'],
      },
      {
        id: 'strength-c',
        name: 'Oberkörper Druck',
        machineIds: ['chest-press', 'shoulder-press', 'butterfly', 'abdominal'],
      },
    ],
    targetSets: 3,
    repMin: 8,
    repMax: 12,
    weightStep: 2.5,
    approvedBy: 'Trainerteam Pilot Studio',
  },
  {
    studioId: studioTheme.studioId,
    id: 'active-circuit',
    name: 'Active Circuit',
    description: 'Ein zügiger Maschinenzirkel mit moderaten Pausen für Kraftausdauer.',
    goals: ['endurance', 'weight_control'],
    levels: ['beginner', 'intermediate', 'advanced'],
    supportedDays: [2, 3, 4, 5],
    supportedDurations: [30, 45, 60],
    machineIds: ['leg-press', 'chest-press', 'lat-pulldown', 'seated-row', 'shoulder-press', 'abdominal'],
    dayBlueprints: [
      {
        id: 'circuit-a',
        name: 'Aktiv-Zirkel A',
        machineIds: ['leg-press', 'chest-press', 'lat-pulldown', 'abdominal'],
      },
      {
        id: 'circuit-b',
        name: 'Aktiv-Zirkel B',
        machineIds: ['hack-squat', 'shoulder-press', 'seated-row', 'back-extension'],
      },
    ],
    targetSets: 2,
    repMin: 12,
    repMax: 15,
    weightStep: 2.5,
    approvedBy: 'Trainerteam Pilot Studio',
  },
]
